#!/bin/sh
### BEGIN INIT INFO
# Provides:          elasticsearch
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

es_dir="/web/soft/elasticsearch-6.5.4"
esconf_dir="/web/soft/elasticsearch-6.5.4/config"
user="amt"

name=elasticsearch
es_pid=$(ps -fe | grep "$esconf_dir" | grep -v grep | tr -s " " | cut -d" " -f2)
stdout_log="$es_dir/logs/$name.log"
stderr_log="$es_dir/logs/$name.err"

export JAVA_HOME=/web/soft/jdk1.8.0_171/
export PATH=$JAVA_HOME/bin:$PATH

chmod 777 /tmp
chown -R amt: $es_dir
chmod -R 755 $es_dir

cmd="$es_dir/bin/elasticsearch -d"

case "$1" in
start)
    if [ -n "${es_pid}" ]; then
        echo Already started, pid "${es_pid}"
    else
        echo "Starting $name"
        su -s /bin/bash - $user -c "$cmd >> $stdout_log 2>> $stderr_log"
    fi
    ;;
stop)
    if [ -n "${es_pid}" ]; then
        echo Stopping $name...With pid "${es_pid}"
        kill "${es_pid}"
    else
        echo "Not running"
    fi
    ;;
restart)
    $0 stop
    sleep 5
    $0 start
    ;;
status)
    if [ -n "${es_pid}" ]; then
        echo Running "${es_pid}"
    else
        echo "Not Running."
        exit 1
    fi
    ;;
*)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
